package com.yu.study.dao.mapper;

import com.yu.study.dao.po.FileInfoPo;
import com.yu.study.dao.po.FileInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int countByExample(FileInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByExample(FileInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByPrimaryKey(String fileInfoUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insert(FileInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insertSelective(FileInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    List<FileInfoPo> selectByExample(FileInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    FileInfoPo selectByPrimaryKey(String fileInfoUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") FileInfoPo record, @Param("example") FileInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExample(@Param("record") FileInfoPo record, @Param("example") FileInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKeySelective(FileInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKey(FileInfoPo record);
}