package com.yu.study.dao.mapper;

import com.yu.study.dao.po.FileInfoRelatePo;
import com.yu.study.dao.po.FileInfoRelatePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileInfoRelatePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int countByExample(FileInfoRelatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByExample(FileInfoRelatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByPrimaryKey(String fileInfoRelateUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insert(FileInfoRelatePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insertSelective(FileInfoRelatePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    List<FileInfoRelatePo> selectByExample(FileInfoRelatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    FileInfoRelatePo selectByPrimaryKey(String fileInfoRelateUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") FileInfoRelatePo record, @Param("example") FileInfoRelatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExample(@Param("record") FileInfoRelatePo record, @Param("example") FileInfoRelatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKeySelective(FileInfoRelatePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKey(FileInfoRelatePo record);
}