package com.yu.study.dao.mapper;

import com.yu.study.dao.po.OrderAddressPo;
import com.yu.study.dao.po.OrderAddressPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderAddressPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int countByExample(OrderAddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByExample(OrderAddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByPrimaryKey(String adressUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insert(OrderAddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insertSelective(OrderAddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    List<OrderAddressPo> selectByExample(OrderAddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    OrderAddressPo selectByPrimaryKey(String adressUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderAddressPo record, @Param("example") OrderAddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExample(@Param("record") OrderAddressPo record, @Param("example") OrderAddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKeySelective(OrderAddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKey(OrderAddressPo record);
}