package com.yu.study.dao.mapper;

import com.yu.study.dao.po.OrderPolicyPo;
import com.yu.study.dao.po.OrderPolicyPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderPolicyPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int countByExample(OrderPolicyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByExample(OrderPolicyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByPrimaryKey(String policyUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insert(OrderPolicyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insertSelective(OrderPolicyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    List<OrderPolicyPo> selectByExample(OrderPolicyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    OrderPolicyPo selectByPrimaryKey(String policyUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderPolicyPo record, @Param("example") OrderPolicyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExample(@Param("record") OrderPolicyPo record, @Param("example") OrderPolicyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKeySelective(OrderPolicyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKey(OrderPolicyPo record);
}