package com.yu.study.dao.mapper;

import com.yu.study.dao.po.OrderAttachInfoPo;
import com.yu.study.dao.po.OrderAttachInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderAttachInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int countByExample(OrderAttachInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByExample(OrderAttachInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByPrimaryKey(String orderAttachUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insert(OrderAttachInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insertSelective(OrderAttachInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    List<OrderAttachInfoPo> selectByExampleWithBLOBs(OrderAttachInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    List<OrderAttachInfoPo> selectByExample(OrderAttachInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    OrderAttachInfoPo selectByPrimaryKey(String orderAttachUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderAttachInfoPo record, @Param("example") OrderAttachInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") OrderAttachInfoPo record, @Param("example") OrderAttachInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExample(@Param("record") OrderAttachInfoPo record, @Param("example") OrderAttachInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKeySelective(OrderAttachInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(OrderAttachInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKey(OrderAttachInfoPo record);
}