package com.yu.study.dao.mapper;

import com.yu.study.dao.po.OrderLogPo;
import com.yu.study.dao.po.OrderLogPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderLogPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int countByExample(OrderLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByExample(OrderLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByPrimaryKey(String logUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insert(OrderLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insertSelective(OrderLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    List<OrderLogPo> selectByExample(OrderLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    OrderLogPo selectByPrimaryKey(String logUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderLogPo record, @Param("example") OrderLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExample(@Param("record") OrderLogPo record, @Param("example") OrderLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKeySelective(OrderLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKey(OrderLogPo record);
}