package com.yu.study.dao.mapper;

import com.yu.study.dao.po.OrderGoodsPo;
import com.yu.study.dao.po.OrderGoodsPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderGoodsPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int countByExample(OrderGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByExample(OrderGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByPrimaryKey(String orderGoodUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insert(OrderGoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insertSelective(OrderGoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    List<OrderGoodsPo> selectByExample(OrderGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    OrderGoodsPo selectByPrimaryKey(String orderGoodUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderGoodsPo record, @Param("example") OrderGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExample(@Param("record") OrderGoodsPo record, @Param("example") OrderGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKeySelective(OrderGoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKey(OrderGoodsPo record);
}