package com.yu.study.dao.mapper;

import com.yu.study.dao.po.OrderRefundPo;
import com.yu.study.dao.po.OrderRefundPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderRefundPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int countByExample(OrderRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByExample(OrderRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int deleteByPrimaryKey(String orderRefundUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insert(OrderRefundPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int insertSelective(OrderRefundPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    List<OrderRefundPo> selectByExample(OrderRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    OrderRefundPo selectByPrimaryKey(String orderRefundUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderRefundPo record, @Param("example") OrderRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByExample(@Param("record") OrderRefundPo record, @Param("example") OrderRefundPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKeySelective(OrderRefundPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    int updateByPrimaryKey(OrderRefundPo record);
}