package com.yu.study.dao.po;

import java.io.Serializable;
import java.util.Date;

public class FileInfoPo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_info_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String fileInfoUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_path
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_size
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_name
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_extention
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String fileExtention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.uploader
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String uploader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.upload_time
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String rowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_info_uid
     *
     * @return the value of file_info.file_info_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getFileInfoUid() {
        return fileInfoUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_info_uid
     *
     * @param fileInfoUid the value for file_info.file_info_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setFileInfoUid(String fileInfoUid) {
        this.fileInfoUid = fileInfoUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_path
     *
     * @return the value of file_info.file_path
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_path
     *
     * @param filePath the value for file_info.file_path
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_size
     *
     * @return the value of file_info.file_size
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_size
     *
     * @param fileSize the value for file_info.file_size
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_name
     *
     * @return the value of file_info.file_name
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_name
     *
     * @param fileName the value for file_info.file_name
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_extention
     *
     * @return the value of file_info.file_extention
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getFileExtention() {
        return fileExtention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_extention
     *
     * @param fileExtention the value for file_info.file_extention
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setFileExtention(String fileExtention) {
        this.fileExtention = fileExtention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.uploader
     *
     * @return the value of file_info.uploader
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.uploader
     *
     * @param uploader the value for file_info.uploader
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setUploader(String uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.upload_time
     *
     * @return the value of file_info.upload_time
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.upload_time
     *
     * @param uploadTime the value for file_info.upload_time
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.row_status
     *
     * @return the value of file_info.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.row_status
     *
     * @param rowStatus the value for file_info.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowStatus(String rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.row_version
     *
     * @return the value of file_info.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.row_version
     *
     * @param rowVersion the value for file_info.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowVersion(Date rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FileInfoPo other = (FileInfoPo) that;
        return (this.getFileInfoUid() == null ? other.getFileInfoUid() == null : this.getFileInfoUid().equals(other.getFileInfoUid()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()))
            && (this.getFileSize() == null ? other.getFileSize() == null : this.getFileSize().equals(other.getFileSize()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getFileExtention() == null ? other.getFileExtention() == null : this.getFileExtention().equals(other.getFileExtention()))
            && (this.getUploader() == null ? other.getUploader() == null : this.getUploader().equals(other.getUploader()))
            && (this.getUploadTime() == null ? other.getUploadTime() == null : this.getUploadTime().equals(other.getUploadTime()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getRowVersion() == null ? other.getRowVersion() == null : this.getRowVersion().equals(other.getRowVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFileInfoUid() == null) ? 0 : getFileInfoUid().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        result = prime * result + ((getFileSize() == null) ? 0 : getFileSize().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getFileExtention() == null) ? 0 : getFileExtention().hashCode());
        result = prime * result + ((getUploader() == null) ? 0 : getUploader().hashCode());
        result = prime * result + ((getUploadTime() == null) ? 0 : getUploadTime().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getRowVersion() == null) ? 0 : getRowVersion().hashCode());
        return result;
    }
}