package com.yu.study.dao.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FileInfoRelatePoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public FileInfoRelatePoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFileInfoRelateUidIsNull() {
            addCriterion("file_info_relate_uid is null");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidIsNotNull() {
            addCriterion("file_info_relate_uid is not null");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidEqualTo(String value) {
            addCriterion("file_info_relate_uid =", value, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidNotEqualTo(String value) {
            addCriterion("file_info_relate_uid <>", value, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidGreaterThan(String value) {
            addCriterion("file_info_relate_uid >", value, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidGreaterThanOrEqualTo(String value) {
            addCriterion("file_info_relate_uid >=", value, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidLessThan(String value) {
            addCriterion("file_info_relate_uid <", value, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidLessThanOrEqualTo(String value) {
            addCriterion("file_info_relate_uid <=", value, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidLike(String value) {
            addCriterion("file_info_relate_uid like", value, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidNotLike(String value) {
            addCriterion("file_info_relate_uid not like", value, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidIn(List<String> values) {
            addCriterion("file_info_relate_uid in", values, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidNotIn(List<String> values) {
            addCriterion("file_info_relate_uid not in", values, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidBetween(String value1, String value2) {
            addCriterion("file_info_relate_uid between", value1, value2, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidNotBetween(String value1, String value2) {
            addCriterion("file_info_relate_uid not between", value1, value2, "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidIsNull() {
            addCriterion("relate_uid is null");
            return (Criteria) this;
        }

        public Criteria andRelateUidIsNotNull() {
            addCriterion("relate_uid is not null");
            return (Criteria) this;
        }

        public Criteria andRelateUidEqualTo(String value) {
            addCriterion("relate_uid =", value, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidNotEqualTo(String value) {
            addCriterion("relate_uid <>", value, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidGreaterThan(String value) {
            addCriterion("relate_uid >", value, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidGreaterThanOrEqualTo(String value) {
            addCriterion("relate_uid >=", value, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidLessThan(String value) {
            addCriterion("relate_uid <", value, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidLessThanOrEqualTo(String value) {
            addCriterion("relate_uid <=", value, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidLike(String value) {
            addCriterion("relate_uid like", value, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidNotLike(String value) {
            addCriterion("relate_uid not like", value, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidIn(List<String> values) {
            addCriterion("relate_uid in", values, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidNotIn(List<String> values) {
            addCriterion("relate_uid not in", values, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidBetween(String value1, String value2) {
            addCriterion("relate_uid between", value1, value2, "relateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidNotBetween(String value1, String value2) {
            addCriterion("relate_uid not between", value1, value2, "relateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidIsNull() {
            addCriterion("file_info_uid is null");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidIsNotNull() {
            addCriterion("file_info_uid is not null");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidEqualTo(String value) {
            addCriterion("file_info_uid =", value, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidNotEqualTo(String value) {
            addCriterion("file_info_uid <>", value, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidGreaterThan(String value) {
            addCriterion("file_info_uid >", value, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidGreaterThanOrEqualTo(String value) {
            addCriterion("file_info_uid >=", value, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidLessThan(String value) {
            addCriterion("file_info_uid <", value, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidLessThanOrEqualTo(String value) {
            addCriterion("file_info_uid <=", value, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidLike(String value) {
            addCriterion("file_info_uid like", value, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidNotLike(String value) {
            addCriterion("file_info_uid not like", value, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidIn(List<String> values) {
            addCriterion("file_info_uid in", values, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidNotIn(List<String> values) {
            addCriterion("file_info_uid not in", values, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidBetween(String value1, String value2) {
            addCriterion("file_info_uid between", value1, value2, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidNotBetween(String value1, String value2) {
            addCriterion("file_info_uid not between", value1, value2, "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andBusinessClassIsNull() {
            addCriterion("business_class is null");
            return (Criteria) this;
        }

        public Criteria andBusinessClassIsNotNull() {
            addCriterion("business_class is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessClassEqualTo(String value) {
            addCriterion("business_class =", value, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassNotEqualTo(String value) {
            addCriterion("business_class <>", value, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassGreaterThan(String value) {
            addCriterion("business_class >", value, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassGreaterThanOrEqualTo(String value) {
            addCriterion("business_class >=", value, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassLessThan(String value) {
            addCriterion("business_class <", value, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassLessThanOrEqualTo(String value) {
            addCriterion("business_class <=", value, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassLike(String value) {
            addCriterion("business_class like", value, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassNotLike(String value) {
            addCriterion("business_class not like", value, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassIn(List<String> values) {
            addCriterion("business_class in", values, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassNotIn(List<String> values) {
            addCriterion("business_class not in", values, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassBetween(String value1, String value2) {
            addCriterion("business_class between", value1, value2, "businessClass");
            return (Criteria) this;
        }

        public Criteria andBusinessClassNotBetween(String value1, String value2) {
            addCriterion("business_class not between", value1, value2, "businessClass");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNull() {
            addCriterion("file_type is null");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNotNull() {
            addCriterion("file_type is not null");
            return (Criteria) this;
        }

        public Criteria andFileTypeEqualTo(Byte value) {
            addCriterion("file_type =", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotEqualTo(Byte value) {
            addCriterion("file_type <>", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThan(Byte value) {
            addCriterion("file_type >", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("file_type >=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThan(Byte value) {
            addCriterion("file_type <", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThanOrEqualTo(Byte value) {
            addCriterion("file_type <=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeIn(List<Byte> values) {
            addCriterion("file_type in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotIn(List<Byte> values) {
            addCriterion("file_type not in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeBetween(Byte value1, Byte value2) {
            addCriterion("file_type between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("file_type not between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNull() {
            addCriterion("order_number is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNotNull() {
            addCriterion("order_number is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberEqualTo(Integer value) {
            addCriterion("order_number =", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotEqualTo(Integer value) {
            addCriterion("order_number <>", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThan(Integer value) {
            addCriterion("order_number >", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_number >=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThan(Integer value) {
            addCriterion("order_number <", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThanOrEqualTo(Integer value) {
            addCriterion("order_number <=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIn(List<Integer> values) {
            addCriterion("order_number in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotIn(List<Integer> values) {
            addCriterion("order_number not in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberBetween(Integer value1, Integer value2) {
            addCriterion("order_number between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("order_number not between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRowStatusIsNull() {
            addCriterion("row_status is null");
            return (Criteria) this;
        }

        public Criteria andRowStatusIsNotNull() {
            addCriterion("row_status is not null");
            return (Criteria) this;
        }

        public Criteria andRowStatusEqualTo(String value) {
            addCriterion("row_status =", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotEqualTo(String value) {
            addCriterion("row_status <>", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusGreaterThan(String value) {
            addCriterion("row_status >", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusGreaterThanOrEqualTo(String value) {
            addCriterion("row_status >=", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusLessThan(String value) {
            addCriterion("row_status <", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusLessThanOrEqualTo(String value) {
            addCriterion("row_status <=", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusLike(String value) {
            addCriterion("row_status like", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotLike(String value) {
            addCriterion("row_status not like", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusIn(List<String> values) {
            addCriterion("row_status in", values, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotIn(List<String> values) {
            addCriterion("row_status not in", values, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusBetween(String value1, String value2) {
            addCriterion("row_status between", value1, value2, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotBetween(String value1, String value2) {
            addCriterion("row_status not between", value1, value2, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNull() {
            addCriterion("row_version is null");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNotNull() {
            addCriterion("row_version is not null");
            return (Criteria) this;
        }

        public Criteria andRowVersionEqualTo(Date value) {
            addCriterion("row_version =", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotEqualTo(Date value) {
            addCriterion("row_version <>", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThan(Date value) {
            addCriterion("row_version >", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThanOrEqualTo(Date value) {
            addCriterion("row_version >=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThan(Date value) {
            addCriterion("row_version <", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThanOrEqualTo(Date value) {
            addCriterion("row_version <=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionIn(List<Date> values) {
            addCriterion("row_version in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotIn(List<Date> values) {
            addCriterion("row_version not in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionBetween(Date value1, Date value2) {
            addCriterion("row_version between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotBetween(Date value1, Date value2) {
            addCriterion("row_version not between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andFileInfoRelateUidLikeInsensitive(String value) {
            addCriterion("upper(file_info_relate_uid) like", value.toUpperCase(), "fileInfoRelateUid");
            return (Criteria) this;
        }

        public Criteria andRelateUidLikeInsensitive(String value) {
            addCriterion("upper(relate_uid) like", value.toUpperCase(), "relateUid");
            return (Criteria) this;
        }

        public Criteria andFileInfoUidLikeInsensitive(String value) {
            addCriterion("upper(file_info_uid) like", value.toUpperCase(), "fileInfoUid");
            return (Criteria) this;
        }

        public Criteria andBusinessClassLikeInsensitive(String value) {
            addCriterion("upper(business_class) like", value.toUpperCase(), "businessClass");
            return (Criteria) this;
        }

        public Criteria andRowStatusLikeInsensitive(String value) {
            addCriterion("upper(row_status) like", value.toUpperCase(), "rowStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_info_relate
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 08 20:53:33 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}