package com.yu.study.dao.po;

import java.io.Serializable;
import java.util.Date;

public class FileInfoRelatePo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info_relate.file_info_relate_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String fileInfoRelateUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info_relate.relate_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String relateUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info_relate.file_info_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String fileInfoUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info_relate.business_class
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String businessClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info_relate.file_type
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Byte fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info_relate.order_number
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info_relate.update_time
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info_relate.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String rowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info_relate.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info_relate.file_info_relate_uid
     *
     * @return the value of file_info_relate.file_info_relate_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getFileInfoRelateUid() {
        return fileInfoRelateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info_relate.file_info_relate_uid
     *
     * @param fileInfoRelateUid the value for file_info_relate.file_info_relate_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setFileInfoRelateUid(String fileInfoRelateUid) {
        this.fileInfoRelateUid = fileInfoRelateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info_relate.relate_uid
     *
     * @return the value of file_info_relate.relate_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getRelateUid() {
        return relateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info_relate.relate_uid
     *
     * @param relateUid the value for file_info_relate.relate_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRelateUid(String relateUid) {
        this.relateUid = relateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info_relate.file_info_uid
     *
     * @return the value of file_info_relate.file_info_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getFileInfoUid() {
        return fileInfoUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info_relate.file_info_uid
     *
     * @param fileInfoUid the value for file_info_relate.file_info_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setFileInfoUid(String fileInfoUid) {
        this.fileInfoUid = fileInfoUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info_relate.business_class
     *
     * @return the value of file_info_relate.business_class
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getBusinessClass() {
        return businessClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info_relate.business_class
     *
     * @param businessClass the value for file_info_relate.business_class
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setBusinessClass(String businessClass) {
        this.businessClass = businessClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info_relate.file_type
     *
     * @return the value of file_info_relate.file_type
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Byte getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info_relate.file_type
     *
     * @param fileType the value for file_info_relate.file_type
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setFileType(Byte fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info_relate.order_number
     *
     * @return the value of file_info_relate.order_number
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info_relate.order_number
     *
     * @param orderNumber the value for file_info_relate.order_number
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info_relate.update_time
     *
     * @return the value of file_info_relate.update_time
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info_relate.update_time
     *
     * @param updateTime the value for file_info_relate.update_time
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info_relate.row_status
     *
     * @return the value of file_info_relate.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info_relate.row_status
     *
     * @param rowStatus the value for file_info_relate.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowStatus(String rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info_relate.row_version
     *
     * @return the value of file_info_relate.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info_relate.row_version
     *
     * @param rowVersion the value for file_info_relate.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowVersion(Date rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FileInfoRelatePo other = (FileInfoRelatePo) that;
        return (this.getFileInfoRelateUid() == null ? other.getFileInfoRelateUid() == null : this.getFileInfoRelateUid().equals(other.getFileInfoRelateUid()))
            && (this.getRelateUid() == null ? other.getRelateUid() == null : this.getRelateUid().equals(other.getRelateUid()))
            && (this.getFileInfoUid() == null ? other.getFileInfoUid() == null : this.getFileInfoUid().equals(other.getFileInfoUid()))
            && (this.getBusinessClass() == null ? other.getBusinessClass() == null : this.getBusinessClass().equals(other.getBusinessClass()))
            && (this.getFileType() == null ? other.getFileType() == null : this.getFileType().equals(other.getFileType()))
            && (this.getOrderNumber() == null ? other.getOrderNumber() == null : this.getOrderNumber().equals(other.getOrderNumber()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getRowVersion() == null ? other.getRowVersion() == null : this.getRowVersion().equals(other.getRowVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info_relate
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFileInfoRelateUid() == null) ? 0 : getFileInfoRelateUid().hashCode());
        result = prime * result + ((getRelateUid() == null) ? 0 : getRelateUid().hashCode());
        result = prime * result + ((getFileInfoUid() == null) ? 0 : getFileInfoUid().hashCode());
        result = prime * result + ((getBusinessClass() == null) ? 0 : getBusinessClass().hashCode());
        result = prime * result + ((getFileType() == null) ? 0 : getFileType().hashCode());
        result = prime * result + ((getOrderNumber() == null) ? 0 : getOrderNumber().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getRowVersion() == null) ? 0 : getRowVersion().hashCode());
        return result;
    }
}