package com.yu.study.dao.po;

import java.io.Serializable;
import java.util.Date;

public class OrderPolicyPo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.policy_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String policyUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String rowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.policy_no
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String policyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.order_good_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String orderGoodUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.policy_company
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String policyCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.policy_product_name
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String policyProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.id_number
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.name
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.birthday
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.sex
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.beneficiary
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String beneficiary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.phone
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.mail
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.effect_date
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date effectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.last_duration
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String lastDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.operate_date
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.operator
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_policy.policy_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Byte policyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.policy_uid
     *
     * @return the value of order_policy.policy_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getPolicyUid() {
        return policyUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.policy_uid
     *
     * @param policyUid the value for order_policy.policy_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setPolicyUid(String policyUid) {
        this.policyUid = policyUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.row_status
     *
     * @return the value of order_policy.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.row_status
     *
     * @param rowStatus the value for order_policy.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowStatus(String rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.row_version
     *
     * @return the value of order_policy.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.row_version
     *
     * @param rowVersion the value for order_policy.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowVersion(Date rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.policy_no
     *
     * @return the value of order_policy.policy_no
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.policy_no
     *
     * @param policyNo the value for order_policy.policy_no
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.order_good_uid
     *
     * @return the value of order_policy.order_good_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getOrderGoodUid() {
        return orderGoodUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.order_good_uid
     *
     * @param orderGoodUid the value for order_policy.order_good_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOrderGoodUid(String orderGoodUid) {
        this.orderGoodUid = orderGoodUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.policy_company
     *
     * @return the value of order_policy.policy_company
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getPolicyCompany() {
        return policyCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.policy_company
     *
     * @param policyCompany the value for order_policy.policy_company
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setPolicyCompany(String policyCompany) {
        this.policyCompany = policyCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.policy_product_name
     *
     * @return the value of order_policy.policy_product_name
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getPolicyProductName() {
        return policyProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.policy_product_name
     *
     * @param policyProductName the value for order_policy.policy_product_name
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setPolicyProductName(String policyProductName) {
        this.policyProductName = policyProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.id_number
     *
     * @return the value of order_policy.id_number
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.id_number
     *
     * @param idNumber the value for order_policy.id_number
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.name
     *
     * @return the value of order_policy.name
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.name
     *
     * @param name the value for order_policy.name
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.birthday
     *
     * @return the value of order_policy.birthday
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.birthday
     *
     * @param birthday the value for order_policy.birthday
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.sex
     *
     * @return the value of order_policy.sex
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.sex
     *
     * @param sex the value for order_policy.sex
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.beneficiary
     *
     * @return the value of order_policy.beneficiary
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getBeneficiary() {
        return beneficiary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.beneficiary
     *
     * @param beneficiary the value for order_policy.beneficiary
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setBeneficiary(String beneficiary) {
        this.beneficiary = beneficiary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.phone
     *
     * @return the value of order_policy.phone
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.phone
     *
     * @param phone the value for order_policy.phone
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.mail
     *
     * @return the value of order_policy.mail
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.mail
     *
     * @param mail the value for order_policy.mail
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.effect_date
     *
     * @return the value of order_policy.effect_date
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getEffectDate() {
        return effectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.effect_date
     *
     * @param effectDate the value for order_policy.effect_date
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setEffectDate(Date effectDate) {
        this.effectDate = effectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.last_duration
     *
     * @return the value of order_policy.last_duration
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getLastDuration() {
        return lastDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.last_duration
     *
     * @param lastDuration the value for order_policy.last_duration
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setLastDuration(String lastDuration) {
        this.lastDuration = lastDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.operate_date
     *
     * @return the value of order_policy.operate_date
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.operate_date
     *
     * @param operateDate the value for order_policy.operate_date
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.operator
     *
     * @return the value of order_policy.operator
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.operator
     *
     * @param operator the value for order_policy.operator
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_policy.policy_status
     *
     * @return the value of order_policy.policy_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Byte getPolicyStatus() {
        return policyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_policy.policy_status
     *
     * @param policyStatus the value for order_policy.policy_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setPolicyStatus(Byte policyStatus) {
        this.policyStatus = policyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderPolicyPo other = (OrderPolicyPo) that;
        return (this.getPolicyUid() == null ? other.getPolicyUid() == null : this.getPolicyUid().equals(other.getPolicyUid()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getRowVersion() == null ? other.getRowVersion() == null : this.getRowVersion().equals(other.getRowVersion()))
            && (this.getPolicyNo() == null ? other.getPolicyNo() == null : this.getPolicyNo().equals(other.getPolicyNo()))
            && (this.getOrderGoodUid() == null ? other.getOrderGoodUid() == null : this.getOrderGoodUid().equals(other.getOrderGoodUid()))
            && (this.getPolicyCompany() == null ? other.getPolicyCompany() == null : this.getPolicyCompany().equals(other.getPolicyCompany()))
            && (this.getPolicyProductName() == null ? other.getPolicyProductName() == null : this.getPolicyProductName().equals(other.getPolicyProductName()))
            && (this.getIdNumber() == null ? other.getIdNumber() == null : this.getIdNumber().equals(other.getIdNumber()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getBeneficiary() == null ? other.getBeneficiary() == null : this.getBeneficiary().equals(other.getBeneficiary()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getMail() == null ? other.getMail() == null : this.getMail().equals(other.getMail()))
            && (this.getEffectDate() == null ? other.getEffectDate() == null : this.getEffectDate().equals(other.getEffectDate()))
            && (this.getLastDuration() == null ? other.getLastDuration() == null : this.getLastDuration().equals(other.getLastDuration()))
            && (this.getOperateDate() == null ? other.getOperateDate() == null : this.getOperateDate().equals(other.getOperateDate()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getPolicyStatus() == null ? other.getPolicyStatus() == null : this.getPolicyStatus().equals(other.getPolicyStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_policy
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPolicyUid() == null) ? 0 : getPolicyUid().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getRowVersion() == null) ? 0 : getRowVersion().hashCode());
        result = prime * result + ((getPolicyNo() == null) ? 0 : getPolicyNo().hashCode());
        result = prime * result + ((getOrderGoodUid() == null) ? 0 : getOrderGoodUid().hashCode());
        result = prime * result + ((getPolicyCompany() == null) ? 0 : getPolicyCompany().hashCode());
        result = prime * result + ((getPolicyProductName() == null) ? 0 : getPolicyProductName().hashCode());
        result = prime * result + ((getIdNumber() == null) ? 0 : getIdNumber().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getBeneficiary() == null) ? 0 : getBeneficiary().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getMail() == null) ? 0 : getMail().hashCode());
        result = prime * result + ((getEffectDate() == null) ? 0 : getEffectDate().hashCode());
        result = prime * result + ((getLastDuration() == null) ? 0 : getLastDuration().hashCode());
        result = prime * result + ((getOperateDate() == null) ? 0 : getOperateDate().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getPolicyStatus() == null) ? 0 : getPolicyStatus().hashCode());
        return result;
    }
}