package com.yu.study.dao.po;

import java.io.Serializable;
import java.util.Date;

public class OrderAddressPo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.adress_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String adressUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String rowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.user_id
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.receiver
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.receiver_phone
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.user_province
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String userProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.user_city
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String userCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.user_district
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String userDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.receiver_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.used_default
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Integer usedDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address.latest_used_time
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date latestUsedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.adress_uid
     *
     * @return the value of order_address.adress_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getAdressUid() {
        return adressUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.adress_uid
     *
     * @param adressUid the value for order_address.adress_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setAdressUid(String adressUid) {
        this.adressUid = adressUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.row_status
     *
     * @return the value of order_address.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.row_status
     *
     * @param rowStatus the value for order_address.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowStatus(String rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.row_version
     *
     * @return the value of order_address.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.row_version
     *
     * @param rowVersion the value for order_address.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowVersion(Date rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.user_id
     *
     * @return the value of order_address.user_id
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.user_id
     *
     * @param userId the value for order_address.user_id
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.receiver
     *
     * @return the value of order_address.receiver
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.receiver
     *
     * @param receiver the value for order_address.receiver
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.receiver_phone
     *
     * @return the value of order_address.receiver_phone
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.receiver_phone
     *
     * @param receiverPhone the value for order_address.receiver_phone
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.user_province
     *
     * @return the value of order_address.user_province
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getUserProvince() {
        return userProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.user_province
     *
     * @param userProvince the value for order_address.user_province
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setUserProvince(String userProvince) {
        this.userProvince = userProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.user_city
     *
     * @return the value of order_address.user_city
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getUserCity() {
        return userCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.user_city
     *
     * @param userCity the value for order_address.user_city
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setUserCity(String userCity) {
        this.userCity = userCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.user_district
     *
     * @return the value of order_address.user_district
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getUserDistrict() {
        return userDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.user_district
     *
     * @param userDistrict the value for order_address.user_district
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setUserDistrict(String userDistrict) {
        this.userDistrict = userDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.receiver_address
     *
     * @return the value of order_address.receiver_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.receiver_address
     *
     * @param receiverAddress the value for order_address.receiver_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.used_default
     *
     * @return the value of order_address.used_default
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Integer getUsedDefault() {
        return usedDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.used_default
     *
     * @param usedDefault the value for order_address.used_default
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setUsedDefault(Integer usedDefault) {
        this.usedDefault = usedDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address.latest_used_time
     *
     * @return the value of order_address.latest_used_time
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getLatestUsedTime() {
        return latestUsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address.latest_used_time
     *
     * @param latestUsedTime the value for order_address.latest_used_time
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setLatestUsedTime(Date latestUsedTime) {
        this.latestUsedTime = latestUsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderAddressPo other = (OrderAddressPo) that;
        return (this.getAdressUid() == null ? other.getAdressUid() == null : this.getAdressUid().equals(other.getAdressUid()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getRowVersion() == null ? other.getRowVersion() == null : this.getRowVersion().equals(other.getRowVersion()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getReceiver() == null ? other.getReceiver() == null : this.getReceiver().equals(other.getReceiver()))
            && (this.getReceiverPhone() == null ? other.getReceiverPhone() == null : this.getReceiverPhone().equals(other.getReceiverPhone()))
            && (this.getUserProvince() == null ? other.getUserProvince() == null : this.getUserProvince().equals(other.getUserProvince()))
            && (this.getUserCity() == null ? other.getUserCity() == null : this.getUserCity().equals(other.getUserCity()))
            && (this.getUserDistrict() == null ? other.getUserDistrict() == null : this.getUserDistrict().equals(other.getUserDistrict()))
            && (this.getReceiverAddress() == null ? other.getReceiverAddress() == null : this.getReceiverAddress().equals(other.getReceiverAddress()))
            && (this.getUsedDefault() == null ? other.getUsedDefault() == null : this.getUsedDefault().equals(other.getUsedDefault()))
            && (this.getLatestUsedTime() == null ? other.getLatestUsedTime() == null : this.getLatestUsedTime().equals(other.getLatestUsedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAdressUid() == null) ? 0 : getAdressUid().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getRowVersion() == null) ? 0 : getRowVersion().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getReceiver() == null) ? 0 : getReceiver().hashCode());
        result = prime * result + ((getReceiverPhone() == null) ? 0 : getReceiverPhone().hashCode());
        result = prime * result + ((getUserProvince() == null) ? 0 : getUserProvince().hashCode());
        result = prime * result + ((getUserCity() == null) ? 0 : getUserCity().hashCode());
        result = prime * result + ((getUserDistrict() == null) ? 0 : getUserDistrict().hashCode());
        result = prime * result + ((getReceiverAddress() == null) ? 0 : getReceiverAddress().hashCode());
        result = prime * result + ((getUsedDefault() == null) ? 0 : getUsedDefault().hashCode());
        result = prime * result + ((getLatestUsedTime() == null) ? 0 : getLatestUsedTime().hashCode());
        return result;
    }
}