package com.yu.study.dao.po;

import java.io.Serializable;
import java.util.Date;

public class OrderLogPo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.log_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String logUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String rowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.order_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String orderUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.operate_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String operateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.operator
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.operate_date
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.log_type
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.description
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.remark
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.log_uid
     *
     * @return the value of order_log.log_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getLogUid() {
        return logUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.log_uid
     *
     * @param logUid the value for order_log.log_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setLogUid(String logUid) {
        this.logUid = logUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.row_status
     *
     * @return the value of order_log.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.row_status
     *
     * @param rowStatus the value for order_log.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowStatus(String rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.row_version
     *
     * @return the value of order_log.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.row_version
     *
     * @param rowVersion the value for order_log.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowVersion(Date rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.order_uid
     *
     * @return the value of order_log.order_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getOrderUid() {
        return orderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.order_uid
     *
     * @param orderUid the value for order_log.order_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOrderUid(String orderUid) {
        this.orderUid = orderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.operate_status
     *
     * @return the value of order_log.operate_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getOperateStatus() {
        return operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.operate_status
     *
     * @param operateStatus the value for order_log.operate_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOperateStatus(String operateStatus) {
        this.operateStatus = operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.operator
     *
     * @return the value of order_log.operator
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.operator
     *
     * @param operator the value for order_log.operator
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.operate_date
     *
     * @return the value of order_log.operate_date
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.operate_date
     *
     * @param operateDate the value for order_log.operate_date
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.log_type
     *
     * @return the value of order_log.log_type
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.log_type
     *
     * @param logType the value for order_log.log_type
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.description
     *
     * @return the value of order_log.description
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.description
     *
     * @param description the value for order_log.description
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.remark
     *
     * @return the value of order_log.remark
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.remark
     *
     * @param remark the value for order_log.remark
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderLogPo other = (OrderLogPo) that;
        return (this.getLogUid() == null ? other.getLogUid() == null : this.getLogUid().equals(other.getLogUid()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getRowVersion() == null ? other.getRowVersion() == null : this.getRowVersion().equals(other.getRowVersion()))
            && (this.getOrderUid() == null ? other.getOrderUid() == null : this.getOrderUid().equals(other.getOrderUid()))
            && (this.getOperateStatus() == null ? other.getOperateStatus() == null : this.getOperateStatus().equals(other.getOperateStatus()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getOperateDate() == null ? other.getOperateDate() == null : this.getOperateDate().equals(other.getOperateDate()))
            && (this.getLogType() == null ? other.getLogType() == null : this.getLogType().equals(other.getLogType()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLogUid() == null) ? 0 : getLogUid().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getRowVersion() == null) ? 0 : getRowVersion().hashCode());
        result = prime * result + ((getOrderUid() == null) ? 0 : getOrderUid().hashCode());
        result = prime * result + ((getOperateStatus() == null) ? 0 : getOperateStatus().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getOperateDate() == null) ? 0 : getOperateDate().hashCode());
        result = prime * result + ((getLogType() == null) ? 0 : getLogType().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}