package com.yu.study.dao.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderAddressPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public OrderAddressPoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdressUidIsNull() {
            addCriterion("adress_uid is null");
            return (Criteria) this;
        }

        public Criteria andAdressUidIsNotNull() {
            addCriterion("adress_uid is not null");
            return (Criteria) this;
        }

        public Criteria andAdressUidEqualTo(String value) {
            addCriterion("adress_uid =", value, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidNotEqualTo(String value) {
            addCriterion("adress_uid <>", value, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidGreaterThan(String value) {
            addCriterion("adress_uid >", value, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidGreaterThanOrEqualTo(String value) {
            addCriterion("adress_uid >=", value, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidLessThan(String value) {
            addCriterion("adress_uid <", value, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidLessThanOrEqualTo(String value) {
            addCriterion("adress_uid <=", value, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidLike(String value) {
            addCriterion("adress_uid like", value, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidNotLike(String value) {
            addCriterion("adress_uid not like", value, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidIn(List<String> values) {
            addCriterion("adress_uid in", values, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidNotIn(List<String> values) {
            addCriterion("adress_uid not in", values, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidBetween(String value1, String value2) {
            addCriterion("adress_uid between", value1, value2, "adressUid");
            return (Criteria) this;
        }

        public Criteria andAdressUidNotBetween(String value1, String value2) {
            addCriterion("adress_uid not between", value1, value2, "adressUid");
            return (Criteria) this;
        }

        public Criteria andRowStatusIsNull() {
            addCriterion("row_status is null");
            return (Criteria) this;
        }

        public Criteria andRowStatusIsNotNull() {
            addCriterion("row_status is not null");
            return (Criteria) this;
        }

        public Criteria andRowStatusEqualTo(String value) {
            addCriterion("row_status =", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotEqualTo(String value) {
            addCriterion("row_status <>", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusGreaterThan(String value) {
            addCriterion("row_status >", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusGreaterThanOrEqualTo(String value) {
            addCriterion("row_status >=", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusLessThan(String value) {
            addCriterion("row_status <", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusLessThanOrEqualTo(String value) {
            addCriterion("row_status <=", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusLike(String value) {
            addCriterion("row_status like", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotLike(String value) {
            addCriterion("row_status not like", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusIn(List<String> values) {
            addCriterion("row_status in", values, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotIn(List<String> values) {
            addCriterion("row_status not in", values, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusBetween(String value1, String value2) {
            addCriterion("row_status between", value1, value2, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotBetween(String value1, String value2) {
            addCriterion("row_status not between", value1, value2, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNull() {
            addCriterion("row_version is null");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNotNull() {
            addCriterion("row_version is not null");
            return (Criteria) this;
        }

        public Criteria andRowVersionEqualTo(Date value) {
            addCriterion("row_version =", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotEqualTo(Date value) {
            addCriterion("row_version <>", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThan(Date value) {
            addCriterion("row_version >", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThanOrEqualTo(Date value) {
            addCriterion("row_version >=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThan(Date value) {
            addCriterion("row_version <", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThanOrEqualTo(Date value) {
            addCriterion("row_version <=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionIn(List<Date> values) {
            addCriterion("row_version in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotIn(List<Date> values) {
            addCriterion("row_version not in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionBetween(Date value1, Date value2) {
            addCriterion("row_version between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotBetween(Date value1, Date value2) {
            addCriterion("row_version not between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andReceiverIsNull() {
            addCriterion("receiver is null");
            return (Criteria) this;
        }

        public Criteria andReceiverIsNotNull() {
            addCriterion("receiver is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverEqualTo(String value) {
            addCriterion("receiver =", value, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverNotEqualTo(String value) {
            addCriterion("receiver <>", value, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverGreaterThan(String value) {
            addCriterion("receiver >", value, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverGreaterThanOrEqualTo(String value) {
            addCriterion("receiver >=", value, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverLessThan(String value) {
            addCriterion("receiver <", value, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverLessThanOrEqualTo(String value) {
            addCriterion("receiver <=", value, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverLike(String value) {
            addCriterion("receiver like", value, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverNotLike(String value) {
            addCriterion("receiver not like", value, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverIn(List<String> values) {
            addCriterion("receiver in", values, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverNotIn(List<String> values) {
            addCriterion("receiver not in", values, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverBetween(String value1, String value2) {
            addCriterion("receiver between", value1, value2, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverNotBetween(String value1, String value2) {
            addCriterion("receiver not between", value1, value2, "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneIsNull() {
            addCriterion("receiver_phone is null");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneIsNotNull() {
            addCriterion("receiver_phone is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneEqualTo(String value) {
            addCriterion("receiver_phone =", value, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneNotEqualTo(String value) {
            addCriterion("receiver_phone <>", value, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneGreaterThan(String value) {
            addCriterion("receiver_phone >", value, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("receiver_phone >=", value, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneLessThan(String value) {
            addCriterion("receiver_phone <", value, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneLessThanOrEqualTo(String value) {
            addCriterion("receiver_phone <=", value, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneLike(String value) {
            addCriterion("receiver_phone like", value, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneNotLike(String value) {
            addCriterion("receiver_phone not like", value, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneIn(List<String> values) {
            addCriterion("receiver_phone in", values, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneNotIn(List<String> values) {
            addCriterion("receiver_phone not in", values, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneBetween(String value1, String value2) {
            addCriterion("receiver_phone between", value1, value2, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneNotBetween(String value1, String value2) {
            addCriterion("receiver_phone not between", value1, value2, "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andUserProvinceIsNull() {
            addCriterion("user_province is null");
            return (Criteria) this;
        }

        public Criteria andUserProvinceIsNotNull() {
            addCriterion("user_province is not null");
            return (Criteria) this;
        }

        public Criteria andUserProvinceEqualTo(String value) {
            addCriterion("user_province =", value, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceNotEqualTo(String value) {
            addCriterion("user_province <>", value, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceGreaterThan(String value) {
            addCriterion("user_province >", value, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("user_province >=", value, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceLessThan(String value) {
            addCriterion("user_province <", value, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceLessThanOrEqualTo(String value) {
            addCriterion("user_province <=", value, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceLike(String value) {
            addCriterion("user_province like", value, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceNotLike(String value) {
            addCriterion("user_province not like", value, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceIn(List<String> values) {
            addCriterion("user_province in", values, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceNotIn(List<String> values) {
            addCriterion("user_province not in", values, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceBetween(String value1, String value2) {
            addCriterion("user_province between", value1, value2, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserProvinceNotBetween(String value1, String value2) {
            addCriterion("user_province not between", value1, value2, "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserCityIsNull() {
            addCriterion("user_city is null");
            return (Criteria) this;
        }

        public Criteria andUserCityIsNotNull() {
            addCriterion("user_city is not null");
            return (Criteria) this;
        }

        public Criteria andUserCityEqualTo(String value) {
            addCriterion("user_city =", value, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityNotEqualTo(String value) {
            addCriterion("user_city <>", value, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityGreaterThan(String value) {
            addCriterion("user_city >", value, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityGreaterThanOrEqualTo(String value) {
            addCriterion("user_city >=", value, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityLessThan(String value) {
            addCriterion("user_city <", value, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityLessThanOrEqualTo(String value) {
            addCriterion("user_city <=", value, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityLike(String value) {
            addCriterion("user_city like", value, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityNotLike(String value) {
            addCriterion("user_city not like", value, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityIn(List<String> values) {
            addCriterion("user_city in", values, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityNotIn(List<String> values) {
            addCriterion("user_city not in", values, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityBetween(String value1, String value2) {
            addCriterion("user_city between", value1, value2, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserCityNotBetween(String value1, String value2) {
            addCriterion("user_city not between", value1, value2, "userCity");
            return (Criteria) this;
        }

        public Criteria andUserDistrictIsNull() {
            addCriterion("user_district is null");
            return (Criteria) this;
        }

        public Criteria andUserDistrictIsNotNull() {
            addCriterion("user_district is not null");
            return (Criteria) this;
        }

        public Criteria andUserDistrictEqualTo(String value) {
            addCriterion("user_district =", value, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictNotEqualTo(String value) {
            addCriterion("user_district <>", value, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictGreaterThan(String value) {
            addCriterion("user_district >", value, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("user_district >=", value, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictLessThan(String value) {
            addCriterion("user_district <", value, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictLessThanOrEqualTo(String value) {
            addCriterion("user_district <=", value, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictLike(String value) {
            addCriterion("user_district like", value, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictNotLike(String value) {
            addCriterion("user_district not like", value, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictIn(List<String> values) {
            addCriterion("user_district in", values, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictNotIn(List<String> values) {
            addCriterion("user_district not in", values, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictBetween(String value1, String value2) {
            addCriterion("user_district between", value1, value2, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andUserDistrictNotBetween(String value1, String value2) {
            addCriterion("user_district not between", value1, value2, "userDistrict");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressIsNull() {
            addCriterion("receiver_address is null");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressIsNotNull() {
            addCriterion("receiver_address is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressEqualTo(String value) {
            addCriterion("receiver_address =", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressNotEqualTo(String value) {
            addCriterion("receiver_address <>", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressGreaterThan(String value) {
            addCriterion("receiver_address >", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressGreaterThanOrEqualTo(String value) {
            addCriterion("receiver_address >=", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressLessThan(String value) {
            addCriterion("receiver_address <", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressLessThanOrEqualTo(String value) {
            addCriterion("receiver_address <=", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressLike(String value) {
            addCriterion("receiver_address like", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressNotLike(String value) {
            addCriterion("receiver_address not like", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressIn(List<String> values) {
            addCriterion("receiver_address in", values, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressNotIn(List<String> values) {
            addCriterion("receiver_address not in", values, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressBetween(String value1, String value2) {
            addCriterion("receiver_address between", value1, value2, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressNotBetween(String value1, String value2) {
            addCriterion("receiver_address not between", value1, value2, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultIsNull() {
            addCriterion("used_default is null");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultIsNotNull() {
            addCriterion("used_default is not null");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultEqualTo(Integer value) {
            addCriterion("used_default =", value, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultNotEqualTo(Integer value) {
            addCriterion("used_default <>", value, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultGreaterThan(Integer value) {
            addCriterion("used_default >", value, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultGreaterThanOrEqualTo(Integer value) {
            addCriterion("used_default >=", value, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultLessThan(Integer value) {
            addCriterion("used_default <", value, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultLessThanOrEqualTo(Integer value) {
            addCriterion("used_default <=", value, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultIn(List<Integer> values) {
            addCriterion("used_default in", values, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultNotIn(List<Integer> values) {
            addCriterion("used_default not in", values, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultBetween(Integer value1, Integer value2) {
            addCriterion("used_default between", value1, value2, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andUsedDefaultNotBetween(Integer value1, Integer value2) {
            addCriterion("used_default not between", value1, value2, "usedDefault");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeIsNull() {
            addCriterion("latest_used_time is null");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeIsNotNull() {
            addCriterion("latest_used_time is not null");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeEqualTo(Date value) {
            addCriterion("latest_used_time =", value, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeNotEqualTo(Date value) {
            addCriterion("latest_used_time <>", value, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeGreaterThan(Date value) {
            addCriterion("latest_used_time >", value, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("latest_used_time >=", value, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeLessThan(Date value) {
            addCriterion("latest_used_time <", value, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeLessThanOrEqualTo(Date value) {
            addCriterion("latest_used_time <=", value, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeIn(List<Date> values) {
            addCriterion("latest_used_time in", values, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeNotIn(List<Date> values) {
            addCriterion("latest_used_time not in", values, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeBetween(Date value1, Date value2) {
            addCriterion("latest_used_time between", value1, value2, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andLatestUsedTimeNotBetween(Date value1, Date value2) {
            addCriterion("latest_used_time not between", value1, value2, "latestUsedTime");
            return (Criteria) this;
        }

        public Criteria andAdressUidLikeInsensitive(String value) {
            addCriterion("upper(adress_uid) like", value.toUpperCase(), "adressUid");
            return (Criteria) this;
        }

        public Criteria andRowStatusLikeInsensitive(String value) {
            addCriterion("upper(row_status) like", value.toUpperCase(), "rowStatus");
            return (Criteria) this;
        }

        public Criteria andUserIdLikeInsensitive(String value) {
            addCriterion("upper(user_id) like", value.toUpperCase(), "userId");
            return (Criteria) this;
        }

        public Criteria andReceiverLikeInsensitive(String value) {
            addCriterion("upper(receiver) like", value.toUpperCase(), "receiver");
            return (Criteria) this;
        }

        public Criteria andReceiverPhoneLikeInsensitive(String value) {
            addCriterion("upper(receiver_phone) like", value.toUpperCase(), "receiverPhone");
            return (Criteria) this;
        }

        public Criteria andUserProvinceLikeInsensitive(String value) {
            addCriterion("upper(user_province) like", value.toUpperCase(), "userProvince");
            return (Criteria) this;
        }

        public Criteria andUserCityLikeInsensitive(String value) {
            addCriterion("upper(user_city) like", value.toUpperCase(), "userCity");
            return (Criteria) this;
        }

        public Criteria andUserDistrictLikeInsensitive(String value) {
            addCriterion("upper(user_district) like", value.toUpperCase(), "userDistrict");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressLikeInsensitive(String value) {
            addCriterion("upper(receiver_address) like", value.toUpperCase(), "receiverAddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_address
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 08 20:53:33 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_address
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}