package com.yu.study.dao.po;

import java.io.Serializable;
import java.util.Date;

public class OrderAttachInfoPo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_attach_info.order_attach_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String orderAttachUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_attach_info.order_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String orderUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_attach_info.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String rowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_attach_info.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private Date rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_attach_info.attch_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private String attchInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_attach_info.order_attach_uid
     *
     * @return the value of order_attach_info.order_attach_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getOrderAttachUid() {
        return orderAttachUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_attach_info.order_attach_uid
     *
     * @param orderAttachUid the value for order_attach_info.order_attach_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOrderAttachUid(String orderAttachUid) {
        this.orderAttachUid = orderAttachUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_attach_info.order_uid
     *
     * @return the value of order_attach_info.order_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getOrderUid() {
        return orderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_attach_info.order_uid
     *
     * @param orderUid the value for order_attach_info.order_uid
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setOrderUid(String orderUid) {
        this.orderUid = orderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_attach_info.row_status
     *
     * @return the value of order_attach_info.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_attach_info.row_status
     *
     * @param rowStatus the value for order_attach_info.row_status
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowStatus(String rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_attach_info.row_version
     *
     * @return the value of order_attach_info.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public Date getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_attach_info.row_version
     *
     * @param rowVersion the value for order_attach_info.row_version
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setRowVersion(Date rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_attach_info.attch_info
     *
     * @return the value of order_attach_info.attch_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public String getAttchInfo() {
        return attchInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_attach_info.attch_info
     *
     * @param attchInfo the value for order_attach_info.attch_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    public void setAttchInfo(String attchInfo) {
        this.attchInfo = attchInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderAttachInfoPo other = (OrderAttachInfoPo) that;
        return (this.getOrderAttachUid() == null ? other.getOrderAttachUid() == null : this.getOrderAttachUid().equals(other.getOrderAttachUid()))
            && (this.getOrderUid() == null ? other.getOrderUid() == null : this.getOrderUid().equals(other.getOrderUid()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getRowVersion() == null ? other.getRowVersion() == null : this.getRowVersion().equals(other.getRowVersion()))
            && (this.getAttchInfo() == null ? other.getAttchInfo() == null : this.getAttchInfo().equals(other.getAttchInfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attach_info
     *
     * @mbggenerated Wed Nov 08 20:53:33 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderAttachUid() == null) ? 0 : getOrderAttachUid().hashCode());
        result = prime * result + ((getOrderUid() == null) ? 0 : getOrderUid().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getRowVersion() == null) ? 0 : getRowVersion().hashCode());
        result = prime * result + ((getAttchInfo() == null) ? 0 : getAttchInfo().hashCode());
        return result;
    }
}